$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: without-scoring-05
model:
  path: ../../model-1/model/
environment:
  # conda_file: ../../model-1/environment/conda.yaml
  # image: mcr.microsoft.com/azureml/mlflow-ubuntu20.04-py38-cpu-inference
  # image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
  build: 
    path: image_build_with_reqirements
    dockerfile_path: Dockerfile
instance_type: Standard_DS3_v2
instance_count: 1
